baseurl = "https://yacdaniel.github.io/yacdaniel.com/"
title = "Yacdaniel Hurtado"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
googleAnalytics = "UA-96459276-1"

[taxonomies]
  series = "series"

[params]
    author = "Yacdaniel Hurtado"
    avatar = "avatar.jpg"
    favicon = "favicon.ico"
    description = """
        open-source enthusiast, QA engineer        
    """
    publicationYear = "2019"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

[outputs]
    section = ["JSON", "HTML"]

[[menu.main]]
    identifier = "linkedin"
    # name = "LinkedIn"
    pre = "<i class='fab fa-linkedin fa-lg'></i>"
    url = "https://linkedin.com/in/yacdaniel"
    weight = 10

[[menu.main]]
    identifier = "github"
    # name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/yacdaniel"
    weight = 20

[[menu.main]]
    identifier = "email"
    # name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:yacdaniel@gmail.com"
    weight = 30
